#######################################################################
#                          PetBlocks                                  #
# 		            	   by Shynixn							      #
#######################################################################

# You can get started and find the permissions at the official documentation.
# https://shynixn.github.io/PetBlocks

############################

# Data-collecting settings

# These are settings to send anonymous stats to https://bstats.org/plugin/bukkit/PetBlocks.
# As this does not have an impact on your PetBlocks experience at all I would like you to set it on true as knowing that my
# plugin gets used by many server helps me focusing on new updates ;)

############################

metrics: true

############################

# Config version

# Change the config-version when you have read the update log and see a change of
# the config.yml. The config.yml does not change every update and the plugin automatically
# checks if your config-version is compatible with the installed plugin.jar.

############################

config-version: 1.0

############################

# Database settings

# All pets are stored in a SQLite database per default which is basically the
# PetBlocks.db file in the plugin folder.
# Available types are 'sqlite' and 'mysql'.
# Use the same mysql database for 2 or more server in order to allow cross server pets.

############################

sql:
  type: 'sqlite'
  host: localhost
  port: 3306
  database: ''
  usessl: false
  username: ''
  password: ''

############################

# Command settings

# There are commands available in PetBlocks you can customize by yourself.
# This means you can disable the command entirely, change the name, description
# and even permission.

############################

commands:
  petblock:
    enabled: true
    command: petblock
    useage: /<command>
    description: Opens the pet GUI.
    permission: petblocks.command.use
    permission-message: You don't have permission
  petblocks:
    enabled: true
    command: petblocks
    useage: /<command>
    description: Command to configure pets.
    permission: petblocks.command.admin
    permission-message: You don't have permission

############################

# Messages settings

# Change the messages of the PetBlocks plugin.

############################

messages:
  prefix: '&2[&aPetBlocks&2]&a '
  default-petname: ":player's pet"
  gui-title: 'PetBlocks'
  naming-suggest-prefix: ''
  naming-suggest-clickable: '&e<<Click here>> '
  naming-suggest-suffix: '&ato rename your pet.'
  naming-suggest-hover: 'Click me to rename your pet.'
  naming-success: '&aYou changed the name of your pet.'
  naming-error: '&cYou cannot name your pet like that.'
  skullnaming-suggest-prefix: ''
  skullnaming-suggest-clickable: '&e<<Click here>> '
  skullnaming-suggest-suffix: '&ato change the skin of your pet.'
  skullnaming-suggest-hover: 'Click me to change the skin of your pet.'
  skullnaming-success: '&aYou changed the skin of your pet.'
  skullnaming-error: '&eThis skin is invalid.'
  called-success: '&aYou have called your pet.'
  toggle-spawn: '&aYour pet has spawned.'
  toggle-despawn: '&aYour pet has despawned.'
  perms-ico-yes: '&aYes'
  perms-ico-no: '&cNo'
  no-perms: '&cYou do not have permissions.'

  ############################

  # Global settings

  # These are global settings which belong to the whole PetBlocks plugin without being specific to a single pet.

  # Please take a look into the official documentation mentioned at the top of this file if you need an explanation for all values.

  ############################

global-configuration:
  respawn-delay: 4
  teleport-delay: 0
  teleport-fall: true
  flying-wall-colliding: true
  apply-pet-on-spawn: false
  overwrite-previous-pet: false
  sounds-other-players: true
  particles-other-players: true
  max-petname-length: 20
  petname-blacklist:
  - 'petty'
  - 'shit'

############################

# Default Pet settings

# The pets of this plugin are very, very customizeable.
# Please take a look into the official documentation mentioned at the top of this file
# in order to configure your pet correctly.

# These are the settings players are starting with when they get their first pet. However,
# you can add all of these settings to the GUI in order to change them per skin or particle or something else.

# You can find a list of all available ais on the documentation.

############################

pet:
  enabled: false
  name: "<player>'s Pet"
  sound-enabled: true
  particle-enabled: true
  skin:
    typename: 2
    datavalue: 0
    unbreakable: false
    owner: ''
  ais:
    1:
      id: 'hopping'
    1:
      id: 'follow-owner'
      max-distance: 50
    2:
      id: 'walking-particle'
      name: 'largesmoke'
      speed: 0.01
      amount: 2
      offx: 0.5
      offy: 0.5
      offz: 0.5
    3:
      id: 'ambient-sound'
      name: 'CHICKEN_IDLE'
      volume: 1.0
      pitch: 1.0
    4:
      id: 'walking-sound'
      name: 'CHICKEN_WALK'
      volume: 1.0
      pitch: 1.0

############################

# World settings

# These settings allow spawning or deny spawning pets in certain worlds.

# world-excluded: Add worlds where the pets should not be able to spawn.
# (When 'all' is added to excluded all worlds are disabled for spawning except the added worlds to included)
# world-included: Add worlds where the pets should be able to spawn.
# (When 'all' is added to included all worlds are enabled for spawning except the added worlds to excluded)

# DO NOT PUT 'all' into both included and excluded!

############################

world:
  excluded:
  - ''
  included:
  - 'all'

############################

# Region settings

# These settings are for the WorldGuard plugin to allow spawning or deny spawning pets in certain regions.
# If you do not have WorldGuard installed, you can ignore these settings.

# region-excluded: Add regions where the pets should not be able to spawn.
# (When 'all' is added to excluded all regions are disabled for spawning except the added regions to included)
# region-included: Add regions where the pets should be able to spawn.
# (When 'all' is added to included all regions are enabled for spawning except the added regions to excluded)

# DO NOT PUT 'all' into both included and excluded!

############################

region:
  excluded:
  - ''
  included:
  - 'all'

############################

# Static GUI settings.

# These settings are global settings for the gui which do not get dynamically parsed.

# Adding new items is not possible for this settings and you can only change the parameters of the existing declared ones.

############################

static-gui:
  empty-slot:
    icon:
      id: 160
      damage: 15
      skin: 'none'
      name: 'none'
      unbreakable: false
      lore:
      - 'none'

      ############################

      # GUI settings.

      # These settings are settings for the GUI which dynamically create the GUI.

      # Adding, Changing and deleting items is possible below, however please take a look into the documentation mentioned at the top
      # of this file in order to change it correctly.

      ############################

gui:
  main:
    player-pet:
      position: 13
      script: 'executing action call-pet'
      icon:
        script: 'executing action copy-pet-skin'
    disable-pet:
      position: 31
      icon:
        id: 397
        damage: 3
        skin: 'http://textures.minecraft.net/texture/f45c9acea8da71b4f252cd4deb5943f49e7dbc0764274b25a6a6f5875baea3'
        name: '&a&lPet enabled'
        lore:
        - '&7Click to disable the pet.'
    enable-pet:
      position: 31
      hidden-when-pet-is-spawned: true
      script: 'executing action call-pet'
      icon:
        id: 397
        damage: 3
        skin: 'textures.minecraft.net/texture/ad5fcd31287d63e7826ea760a7ed154f685dfdc7f3465732a96e619b2e1347'
        name: '&c&lPetdisabled'
        lore:
        - '&7Click to enable the pet.'
    wardrobe:
      position: 10
      script: 'open-page gui.wardrobe'
      icon:
        id: 397
        damage: 3
        skin: 'textures.minecraft.net/texture/55507d6517eff952dd38fa8bc551dd6d6a7a5e4ea134519b44650ac1ffa59c3'
        name: '&6&lPet Customization'
        lore:
        - '&7Change the appearance of your pet.'
    sounds-enabled:
      position: 35
      icon:
        id: 397
        damage: 3
        skin: 'textures.minecraft.net/texture/cb9c706c85572f05efc4170ada791154de2b5378e6252aadc8d43b19c5564'
        name: '&a&lPet unmuted'
        lore:
        - '&7Click to disable the sounds of your pet.'
    sounds-disabled:
      position: 35
      icon:
        id: 397
        damage: 3
        skin: 'textures.minecraft.net/texture/ae7215c45d97d7bc55d9dfa58fcc73f4af74e4b3f5a15b4419127424c4268e'
        name: '&c&lPet muted'
        lore:
        - '&7Click to enable the sounds of your pet.'
    call-pet:
      position: 37
      script: 'executing action call-pet'
      icon:
        id: 420
        name: '&2&lCall'
        lore:
        - '&7Teleports your pet to you.'
    launch-pet:
      position: 24
      icon:
        id: 397
        damage: 3
        skin: 'textures.minecraft.net/texture/996754d330435345aae3a9f063cfca42afb28b7c5c4bb9f294ed2527d961'
        name: '&2&lLaunch'
        lore:
        - '&7Shoot your pet like a cannon.'
    hat-pet:
      position: 6
      icon:
        id: 397
        damage: 3
        skin: 'textures.minecraft.net/texture/9b5f247a7f5b37bbfa488ab4efaddcbad2e526e94fc542b1fe2f7cfeb6e'
        name: '&2&lHat'
        lore:
        - '&7Wear your pet like a hat.'
    ride-pet:
      position: 17
      icon:
        id: 329
        damage: 0
        name: '&2&lRide'
        lore:
        - '&7Start to ride your pet.'
    rename-pet:
      position: 42
      icon:
        id: 421
        damage: 0
        name: '&6&lRename'
        lore:
        - '&7Change the name of your pet.'
    particles-disabled:
      position: 53
      icon:
        id: 397
        damage: 3
        skin: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDFiYzUwZDUyYTJhMmNkYTgxMjAzMWQxMTdmNWZkMDlmOGYwMGRlZWEyNjcxOGZmMTVmNTEyMzE3YjgzNjhmNiJ9fX0='
        name: '&c&lPet particles disabled'
        lore:
        - '&7Click to enable the particles of your pet.'
    back:
      position: 49
      script: 'close-gui'
      icon:
        id: 166
        damage: 0
        name: '&cBack'
        lore:
        - '&7Closes the current window.'
  wardrobe:
    block-skins:
      position: 11
      icon:
        id: 397
        damage: 3
        name: '&e&lSimple block costumes'
        skin: 'http://textures.minecraft.net/texture/c95d37993e594082678472bf9d86823413c250d4332a2c7d8c52de4976b362'
        lore:
        - '&7Use Minecraft blocks as costume.'
    colored-block-skins:
      position: 13
      icon:
        id: 397
        damage: 3
        name: '&a&lColored block costumes'
        skin: 'http://textures.minecraft.net/texture/f1af46febd45c0f4d81e8fa1b66b275d89e272b2ad55c978553a99c733e1ff'
        lore:
        - '&7Use colored Minecraft blocks as costume.'
    player-head-skins:
      position: 15
      icon:
        id: 397
        damage: 3
        name: '&d&lPlayer head costumes'
        skin: 'http://textures.minecraft.net/texture/a0c2549a893726988f3428bef799875ba871688ae64eb0cfdc43f7d6e24c6c'
        lore:
        - '&7Use player heads as costume.'
    minecraft-heads-pet-skins:
      position: 19
      icon:
        id: 397
        damage: 3
        name: '&9&lPet costumes'
        skin: 'http://textures.minecraft.net/texture/fec052be76e39148a27f255ec537dff92018c79744202d60c51bc67d618ae36a'
        lore:
        - "&7Use exclusive pet heads as costume."
        - "&eSponsored by Minecraft-Heads.com"
    minecraft-heads-vehicle-skins:
      position: 23
      icon:
        id: 397
        damage: 3
        name: '&2&lVehicle costumes'
        skin: 'http://textures.minecraft.net/texture/e8778c34fba29652cfac8d3f6fb35c49cbc2362b2b8f1378d83b30f463b181'
        lore:
        - "&7Use exclusive vehicle heads as costume."
        - "&eSponsored by Minecraft-Heads.com"
    minecraft-heads-puppet-skins:
      position: 21
      icon:
        id: 397
        damage: 3
        name: '&b&lPlushie costumes'
        skin: 'http://textures.minecraft.net/texture/3835da2685f7ad3f1919a018976ad56826691e26758a3a55a1918f7f17ad938'
        lore:
        - "&7Use exclusive plushie heads as costume."
        - "&eSponsored by Minecraft-Heads.com"
    headdatabase-skins:
      position: 25
      icon:
        id: 397
        damage: 3
        name: '&c&lHead Database costumes'
        skin: 'http://textures.minecraft.net/texture/3bb612eb495ede2c5ca5178d2d1ecf1ca5a255d25dfc3c254bc47f6848791d8'
        lore:
        - '&7Use heads from an external plugin as costume.'
    suggest-heads:
      position: 43
      icon:
        id: 386
        damage: 0
        name: '&a&lSuggest Heads'
        lore:
        - '&7Submit skins for pets or'
        - '&7make a suggestion for a new pet.'
    enter-custom-head:
      position: 37
      icon:
        id: 397
        damage: 3
        name: '&2&lCustom skin'
        lore:
        - '&7Use the skin of another player as costume.'
    back:
      position: 49
      script: 'close-gui'
      icon:
        id: 166
        damage: 0
        name: '&cBack'
        lore:
        - '&7Closes the current window.'
# Append new items above this line <---