language: java
sudo: true
install:
    - cd /home/travis/build/Shynixn/PetBlocks/
    - mkdir lib
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastStableBuild/artifact/target/BuildTools.jar -P /home/travis/build/Shynixn/PetBlocks/lib/
    - wget https://github.com/MyzelYam/SuperVanish/releases/download/v5.7.0/SuperVanish.jar -P /home/travis/build/Shynixn/PetBlocks/lib/
script:
    - cd /home/travis/build/Shynixn/PetBlocks/lib/
    - java -jar BuildTools.jar --rev 1.8 > /dev/null
    - java -jar BuildTools.jar --rev 1.8.3 > /dev/null
    - java -jar BuildTools.jar --rev 1.8.8 > /dev/null
    - java -jar BuildTools.jar --rev 1.9 > /dev/null
    - java -jar BuildTools.jar --rev 1.9.4 > /dev/null
    - java -jar BuildTools.jar --rev 1.10 > /dev/null
    - java -jar BuildTools.jar --rev 1.11 > /dev/null
    - java -jar BuildTools.jar --rev 1.12
    - cd -
    - mvn compile test
jdk:
  - oraclejdk8
#jdk 8


