language: java
sudo: true
jdk:
  - oraclejdk8
cache:
  timeout: 1000
  directories:
  - $HOME/.m2/repository/org/spigotmc
  - $HOME/.m2/repository/org/mcp
  - $HOME/.m2/repository/me/minebuilders
before_install:
    - chmod +x gradlew
    - sudo /etc/init.d/mysql stop
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    - if [[ $TRAVIS_COMMIT_MESSAGE == *"--refresh-dependencies"* ]]; then ./gradlew downloadDependencies; fi ;
script:
  - ./gradlew clean build
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  #- mvn clean deploy --settings .travis_settings.xml
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#  - wget https://github.com/Shynixn/travis-ci-discord-webhook/raw/master/nexus-query-snapshot.jar
#  - wget https://raw.githubusercontent.com/Shynixn/travis-ci-discord-webhook/master/petblocks.sh
 # - chmod +x petblocks.sh
 # - ./petblocks.sh success $WEBHOOK_URL $WEBHOOK_SNAPSHOT_URL $SNAPSHOT_REPOSITORY_BUKKIT $SNAPSHOT_REPOSITORY_SPONGE
#after_failure:
#  - wget https://raw.githubusercontent.com/Shynixn/travis-ci-discord-webhook/master/send.sh
#  - chmod +x send.sh
 # - ./send.sh failure $WEBHOOK_URL