language: java
sudo: true
install:
    - cd /home/travis/build/Shynixn/PetBlocks/
    - mkdir lib
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastStableBuild/artifact/target/BuildTools.jar -P /home/travis/build/Shynixn/PetBlocks/lib/
before_script:
  - sudo /etc/init.d/mysql stop
script:
    - cd /home/travis/build/Shynixn/PetBlocks/petblocks-sponge-plugin
    - mvn anchornms:generate-mcp-libraries -X
    - cd /home/travis/build/[secure]/PetBlocks/petblocks-sponge-plugin/target/nms-tools/gradle-4.6/bin/gradle
    - ls Cannot run program ""/home/travis/build/[secure]/PetBlocks/petblocks-sponge-plugin/target/nms-tools/gradle-4.6/bin/gradle""
    - ""/home/travis/build/[secure]/PetBlocks/petblocks-sponge-plugin/target/nms-tools/gradle-4.6/bin/gradle""
    - cp target/nms-tools/mcp-1.11.jar /home/travis/build/Shynixn/PetBlocks/lib/mcp-1.11.jar
    - cp target/nms-tools/mcp-1.12.jar /home/travis/build/Shynixn/PetBlocks/lib/mcp-1.12.jar
    - cd /home/travis/build/Shynixn/PetBlocks/lib
    - java -jar BuildTools.jar --rev 1.8 > /dev/null
    - java -jar BuildTools.jar --rev 1.8.3 > /dev/null
    - java -jar BuildTools.jar --rev 1.8.8 > /dev/null
    - java -jar BuildTools.jar --rev 1.9 > /dev/null
    - java -jar BuildTools.jar --rev 1.9.4 > /dev/null
    - java -jar BuildTools.jar --rev 1.10 > /dev/null
    - java -jar BuildTools.jar --rev 1.11 > /dev/null
    - java -jar BuildTools.jar --rev 1.12 > /dev/null
    - cd -
    - mvn install
jdk:
  - oraclejdk8
#jdk 8


