#######################################################################
#                          PetBlocks                                 #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  petblocks:
    usage: "[&9PetBlocks&f] Use /petblocks help to see more info about the plugin."
    description: All commands for the PetBlocks plugin.
    permission-message: You do not have permission.
