#######################################################################
#                          PetBlocks                                 #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  petblocks:
    usage: "[&9PetBlocks&f] Use /petblocks help to see more info about the plugin."
    description: All commands for the PetBlocks plugin.
    permission-message: You do not have permission.


############################
# Script Engine
############################
scriptEngine:
  # Option parameters for the NashornScriptEngine.
  options:
    - "--no-java-access=true"
    - "--persistent-code-cache=true"

############################
# Database
############################
autoSaveIntervalMinutes: 5

############################
# Global pet settings
# For individual pet settings, use the files in the pets folder.
############################
pet:
  # A list of pets the player receives when joining the server. This list may be empty.
  receivePetsOnJoin:
    - name: "pet"
      template: "classic"
  # Render distance of the pet. They become invisible for players outside that range.
  renderDistance: 70
  # Displays a virtual trail of gold blocks, which represents the calculated path of the pet. Can be used for investigating pet paths. Rejoining the server removes the client side blocks.
  showPathfinder: false
  # Amount of milliseconds until the pet registers a new click on it.
  clickCoolDownMs: 70
  # A pathfinder run of a pet starts with a cube snapshot of the world, where a A* pathfinder implementation is applied after wards.
  # This setting defines how big of an area this cube should be. A larger cube requires more processing time and memory consumption.
  # Using a large cube is not recommend, as the pet should teleport or stay at its place when the owner is too far away.
  pathFinderCube:
    x: 28.0
    y: 10.0
    z: 28.0
  # The max amount of blocks, the pet accepts move to orders.
  pathFinderDistance: 20.0
  name:
    # Allows only certain letters as regex validation. (letters, numbers, underline, single quote).
    # Be careful what you allow here, certain pet actions may break (scriptinjection) if you allow special characters.
    regex: "[0-9a-zA-Z_&'\\s]*"
    minLength: 1
    maxLength: 20
    blacklist: # All values which are not allowed inside pet names. You probably need to add a lot of more swear words here for production servers.
      - "fuck"
      - "ass"
