name: PetBlocks
version: 9.1.0
author: Shynixn
main: com.github.shynixn.petblocks.PetBlocksPlugin
softdepend: [ PlaceholderAPI, HeadDatabase]
api-version: 1.13
commands:
  petblocks:
    usage: Use /petblocks help to see more info about the plugin.
    description: All commands for the PetBlocks plugin.
    permission: petblocks.command
    permission-message: You do not have permission.
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.13.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.13.0
  - com.google.inject:guice:5.0.1
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.3.0
  - com.fasterxml.jackson.core:jackson-databind:2.2.3
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2
  - com.google.code.gson:gson:2.8.6
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21
  - com.zaxxer:HikariCP:5.0.1
  - org.openjdk.nashorn:nashorn-core:15.4
  - aopalliance:aopalliance:1.0
