name: PetBlocks
version: 9.0.0
author: Shynixn
main: com.github.shynixn.petblocks.bukkit.PetBlocksPlugin
softdepend: [PlaceholderAPI, HeadDatabase]
commands:
  petblocks:
    description: The command to interact with the PetBlocks plugin.
    useage: /<command>
    permission: petblocks.commmand
    permission-message: You don't have permission.
