name: PetBlocks
version: 7.1.0
author: Shynixn
main: com.github.shynixn.petblocks.bukkit.PetBlocksPlugin
softdepend: [WorldGuard, ClearLag]
commands:
   petblockreload:
      description: Reloads the petblock config and lang file.
      usage: /<command>
      permission: petblocks.command.reload
      permission-message: You don't have permission.